# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-pipelines.yml

trigger:
- main  # Change to your main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
- task: MavenAuthenticate@0  # Authenticate to your Maven feed if needed
  inputs:
    mavenServiceConnection: 'YourServiceConnectionName'  # Optional

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/*.xml'  # Adjust for your test report location
    codeCoverageToolOption: 'jacoco'  # Optional, adjust as needed
    #options: '-Dmaven.test.failure.ignore=true'  # Optional, if you want to ignore test failures

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'  # Directory to publish
    ArtifactName: 'drop'  # Name of the artifact
    publishLocation: 'Container'  # Publish to Azure DevOps

