# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- checkout: self  # Checks out the primary repository
 
- script: |
    # Clone another GitHub repository into a specific path
    git clone https://github.com/sUrey621/DemoBlaze.git $(Build.SourcesDirectory)/MyProjects/MyRepo
 
    # Change directory to the cloned repo
    cd $(Build.SourcesDirectory)/MyProjects/MyRepo
    # Run build or test commands
    ./build.sh  # Example command
  displayName: 'Clone and Build MyRepo'